# Generated by Django 4.2.14 on 2024-08-01 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='IGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('isDataGathered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserHashtagUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hashtag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storage_api.hashtag')),
                ('IGUser', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storage_api.iguser')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ImgData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('tag', models.CharField(max_length=30)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.image')),
            ],
        ),
        migrations.CreateModel(
            name='ImgCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=30)),
                ('topPercent', models.FloatField()),
                ('leftPercent', models.FloatField()),
                ('heightPercent', models.FloatField()),
                ('widthPercent', models.FloatField()),
                ('isDefault', models.BooleanField(default=False)),
                ('recognizedText', models.TextField(blank=True, max_length=10000)),
                ('reviewedText', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.project'),
        ),
        migrations.AddField(
            model_name='iguser',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.project'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.project'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('project', 'userId')},
        ),
        migrations.AlterUniqueTogether(
            name='iguser',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='hashtag',
            unique_together={('project', 'content')},
        ),
    ]
