# Generated by Django 4.2.14 on 2024-07-30 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(unique=True)),
                ('isDataGathered', models.BooleanField(default=False)),
                ('fileName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImgCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=30)),
                ('topX', models.FloatField()),
                ('topY', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
                ('recognizedText', models.TextField(max_length=10000)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.project'),
        ),
        migrations.CreateModel(
            name='IgData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.image')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=500)),
                ('igData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.igdata')),
            ],
        ),
    ]
