# Generated by Django 4.2.14 on 2024-08-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iguser',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
