# Generated by Django 4.2.14 on 2024-07-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0002_remove_image_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='Content',
            new_name='content',
        ),
    ]
