# Generated by Django 4.2.14 on 2024-08-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0003_hashtag_createdfromimage_iguser_createdfromimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhashtaguse',
            old_name='Hashtag',
            new_name='hashtag',
        ),
    ]
