# Generated by Django 4.2.14 on 2024-07-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0003_rename_content_hashtag_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='userId',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('project', 'userId')},
        ),
    ]
