# Generated by Django 4.2.14 on 2024-08-02 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0004_rename_hashtag_userhashtaguse_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhashtaguse',
            old_name='IGUser',
            new_name='igUser',
        ),
    ]
