# Generated by Django 4.2.14 on 2024-08-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0006_alter_hashtag_createdfromimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='createdFromImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_api.image'),
        ),
        migrations.AlterField(
            model_name='iguser',
            name='createdFromImage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage_api.image'),
        ),
    ]
