# Generated by Django 4.2.14 on 2024-08-05 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0008_image_issimilarto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-userId']},
        ),
    ]
