# Generated by Django 4.2.14 on 2024-08-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0009_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='iguser',
            name='alias',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
    ]
