# Generated by Django 4.2.14 on 2024-08-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0010_iguser_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iguser',
            name='alias',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
