# Generated by Django 4.2.14 on 2024-08-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0011_alter_iguser_alias'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgData',
        ),
    ]
