# Generated by Django 4.2.14 on 2024-08-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0012_delete_imgdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhashtaguse',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storage_api.image'),
        ),
        migrations.AlterField(
            model_name='userhashtaguse',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='storage_api.project'),
        ),
    ]
