# Generated by Django 4.2.14 on 2024-08-15 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0013_alter_userhashtaguse_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(max_length=30)),
                ('value', models.TextField(max_length=5000)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.image')),
            ],
        ),
    ]
