# Generated by Django 4.2.14 on 2024-08-15 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0014_imgdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDefaultCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldName', models.CharField(help_text='Questo campo è impostato automaticamente uguale al valore di imgCrop', max_length=30)),
                ('imgCrop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.imgcrop')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.project')),
            ],
            options={
                'unique_together': {('project', 'imgCrop', 'fieldName')},
            },
        ),
    ]
