# Generated by Django 4.2.14 on 2024-08-15 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0015_projectdefaultcrop'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectdefaultcrop',
            unique_together={('project', 'fieldName')},
        ),
    ]
