# Generated by Django 4.2.14 on 2024-08-15 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0017_remove_imgcrop_isdefault_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdefaultcrop',
            name='imgCrop',
        ),
        migrations.AddField(
            model_name='projectdefaultcrop',
            name='heightPercent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdefaultcrop',
            name='leftPercent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdefaultcrop',
            name='topPercent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectdefaultcrop',
            name='widthPercent',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imgcrop',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage_api.image'),
        ),
        migrations.AlterField(
            model_name='projectdefaultcrop',
            name='fieldName',
            field=models.CharField(max_length=30),
        ),
    ]
