# Generated by Django 4.2.14 on 2024-08-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0018_remove_projectdefaultcrop_imgcrop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgcrop',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage_api.image'),
        ),
    ]
