# Generated by Django 4.2.14 on 2024-08-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0019_alter_imgcrop_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='imgdata',
            unique_together={('fieldName', 'image')},
        ),
    ]
