# Generated by Django 4.2.14 on 2024-08-16 13:36

from django.db import migrations, models


def move_file_from_img_file_to_img(apps, schema_editor):
    Image = apps.get_model("storage_api", "image")

    for item in Image.objects.all():
        item.file = item.imagefile.file
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0021_image_file'),
    ]

    operations = [
        migrations.RunPython(move_file_from_img_file_to_img),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(unique=True, upload_to='imgs/'),
        ),
    ]
