# Generated by Django 4.2.14 on 2024-08-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0023_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='average_hash',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
