# Generated by Django 4.2.14 on 2024-08-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0025_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(null=True, upload_to='imgs/'),
        ),
    ]
