# Generated by Django 4.2.15 on 2025-01-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0025_hashtag_user_iguser_user_image_user_imgcrop_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='iguser',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='imgcrop',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='imgdata',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='projectdefaultcrop',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='userhashtaguse',
            old_name='user',
            new_name='author',
        ),
    ]
