# Generated by Django 4.2.15 on 2025-01-30 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storage_api', '0027_alter_hashtag_author_alter_iguser_author_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='iguser',
            unique_together={('project', 'name')},
        ),
        migrations.AlterField(
            model_name='iguser',
            name='alias',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='hashtag',
            unique_together={('project', 'content', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='iguser',
            unique_together={('project', 'name'), ('alias', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('author', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='userhashtaguse',
            unique_together={('image', 'hashtag', 'igUser', 'project', 'author')},
        ),
    ]
