# Generated by Django 4.2.14 on 2024-08-01 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(unique=True, upload_to='images/')),
                ('referencesImage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storage_api.image')),
            ],
        ),
    ]
