# Generated by Django 4.2.14 on 2024-07-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='file',
            field=models.FileField(unique=True, upload_to='images/'),
        ),
    ]
