# Generated by Django 4.2.14 on 2024-07-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage_api', '0003_rename_content_hashtag_content'),
        ('functions_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='referencesImage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='storage_api.image'),
        ),
    ]
