# Generated by Django 4.2.14 on 2024-08-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='average_hash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
