# Generated by Django 4.2.14 on 2024-08-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('functions_api', '0002_imagefile_average_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='average_hash',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
