# Generated by Django 4.2.14 on 2024-08-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functions_api', '0003_alter_imagefile_average_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
